"""Internal ADK-backed structured experts for Design production."""

from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Any, TypeVar

from google.adk.agents import LlmAgent
from google.adk.runners import InMemoryRunner
from google.genai.types import Content, Part
from pydantic import BaseModel, Field

from conf.llm import build_llm, resolve_llm_model_name
from src.production.design.models import (
    DesignBrief,
    DesignGenre,
    DesignSystemSpec,
    LayoutPlan,
    ReferenceAssetEntry,
)
from src.production.design.prompt_catalog import render_prompt_template


class DesignDirectionPlan(BaseModel):
    """Structured output produced before the first Design review."""

    brief: DesignBrief
    design_system: DesignSystemSpec
    layout_plan: LayoutPlan
    notes: str = ""


class HtmlBuildOutput(BaseModel):
    """Structured output produced by the baseline HTML builder expert."""

    title: str = ""
    html: str = Field(description="Complete standalone HTML document.")
    section_fragments: dict[str, str] = Field(default_factory=dict)
    notes: str = ""


SchemaT = TypeVar("SchemaT", bound=BaseModel)


class DesignExpertRuntime:
    """Run internal Design experts through ADK structured-output agents."""

    def __init__(
        self,
        *,
        model_reference: str | None = None,
        app_name: str = "creative_claw_design_internal",
    ) -> None:
        """Initialize the internal Design expert runtime."""
        self.model_reference = model_reference
        self.app_name = app_name

    async def plan_direction(
        self,
        *,
        user_prompt: str,
        design_genre: DesignGenre,
        design_settings: dict[str, Any],
        reference_assets: list[ReferenceAssetEntry],
    ) -> DesignDirectionPlan:
        """Generate brief, design system, and layout plan for the first review."""
        playbook_text = load_design_playbook(design_genre)
        reference_assets_json = _json_dump([asset.model_dump(mode="json") for asset in reference_assets])

        brief_prompt = render_prompt_template(
            "brief_expert",
            {
                "design_genre": design_genre,
                "user_prompt": user_prompt,
                "design_settings_json": _json_dump(design_settings),
                "reference_assets_json": reference_assets_json,
                "playbook_text": playbook_text,
            },
        )
        brief = await self._run_structured_agent(
            agent_name="DesignBriefExpert",
            instruction="You create concise, reviewable Design briefs for HTML-centered production.",
            request_text=brief_prompt,
            output_schema=DesignBrief,
            output_key="design_brief",
        )
        brief.design_genre = design_genre

        design_system_prompt = render_prompt_template(
            "design_system_expert",
            {
                "brief_json": brief.model_dump_json(indent=2),
                "reference_assets_json": reference_assets_json,
                "playbook_text": playbook_text,
            },
        )
        design_system = await self._run_structured_agent(
            agent_name="DesignSystemExpert",
            instruction="You create practical design systems for responsive HTML artifacts.",
            request_text=design_system_prompt,
            output_schema=DesignSystemSpec,
            output_key="design_system",
        )
        if design_system.source == "placeholder":
            design_system.source = "generated"

        layout_prompt = render_prompt_template(
            "layout_planner_expert",
            {
                "brief_json": brief.model_dump_json(indent=2),
                "design_system_json": design_system.model_dump_json(indent=2),
                "reference_assets_json": reference_assets_json,
                "playbook_text": playbook_text,
            },
        )
        layout_plan = await self._run_structured_agent(
            agent_name="LayoutPlannerExpert",
            instruction="You create single-page layout plans with stable HTML section ids.",
            request_text=layout_prompt,
            output_schema=LayoutPlan,
            output_key="layout_plan",
        )

        return DesignDirectionPlan(
            brief=brief,
            design_system=design_system,
            layout_plan=layout_plan,
            notes="Generated by internal structured Design experts.",
        )

    async def build_html(
        self,
        *,
        brief: DesignBrief,
        design_system: DesignSystemSpec,
        layout_plan: LayoutPlan,
        reference_assets: list[ReferenceAssetEntry],
    ) -> HtmlBuildOutput:
        """Generate the baseline single-file HTML artifact."""
        prompt = render_prompt_template(
            "html_builder_expert",
            {
                "brief_json": brief.model_dump_json(indent=2),
                "design_system_json": design_system.model_dump_json(indent=2),
                "layout_plan_json": layout_plan.model_dump_json(indent=2),
                "reference_assets_json": _json_dump([asset.model_dump(mode="json") for asset in reference_assets]),
            },
        )
        output = await self._run_structured_agent(
            agent_name="HtmlBuilderExpert",
            instruction=(
                "You build complete, portable, responsive single-file HTML. "
                "Return only fields requested by the schema."
            ),
            request_text=prompt,
            output_schema=HtmlBuildOutput,
            output_key="html_build_output",
        )
        output.html = normalize_generated_html(output.html)
        return output

    async def _run_structured_agent(
        self,
        *,
        agent_name: str,
        instruction: str,
        request_text: str,
        output_schema: type[SchemaT],
        output_key: str,
    ) -> SchemaT:
        """Run one ADK LlmAgent and parse its structured output."""
        agent = LlmAgent(
            name=agent_name,
            model=build_llm(self.model_reference),
            instruction=instruction,
            include_contents="none",
            output_schema=output_schema,
            output_key=output_key,
        )
        runner = InMemoryRunner(agent=agent, app_name=self.app_name)
        user_id = "design-production"
        session_id = f"{agent_name.lower()}_{uuid.uuid4().hex[:12]}"
        await runner.session_service.create_session(
            app_name=self.app_name,
            user_id=user_id,
            session_id=session_id,
            state={},
        )
        final_text = ""
        async for event in runner.run_async(
            user_id=user_id,
            session_id=session_id,
            new_message=Content(role="user", parts=[Part(text=request_text)]),
        ):
            if event.is_final_response() and event.content and event.content.parts:
                generated_text = next((part.text for part in event.content.parts if part.text), "")
                final_text = str(generated_text or "").strip()

        session = await runner.session_service.get_session(
            app_name=self.app_name,
            user_id=user_id,
            session_id=session_id,
        )
        raw_output = session.state.get(output_key) if session is not None else None
        return _coerce_structured_output(raw_output or final_text, output_schema)

    @property
    def model_name(self) -> str:
        """Return the configured model name for observability."""
        return resolve_llm_model_name(self.model_reference)


def normalize_generated_html(html_text: str) -> str:
    """Return complete HTML text without Markdown fences."""
    text = str(html_text or "").strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    lowered = text.lower()
    if lowered.startswith("<html"):
        text = "<!doctype html>\n" + text
    if "<html" not in lowered or "</html>" not in lowered:
        raise ValueError("HtmlBuilderExpert returned incomplete HTML.")
    return text.rstrip() + "\n"


def load_design_playbook(design_genre: str) -> str:
    """Load the genre playbook text used by internal Design experts."""
    filename_by_genre = {
        "landing_page": "landing_page.md",
        "ui_design": "ui_design.md",
        "product_detail_page": "product_detail_page.md",
    }
    filename = filename_by_genre.get(str(design_genre), "landing_page.md")
    repo_root = Path(__file__).resolve().parents[3]
    playbook_path = repo_root / "playbooks" / "design" / filename
    try:
        return playbook_path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _coerce_structured_output(raw_output: Any, output_schema: type[SchemaT]) -> SchemaT:
    """Coerce ADK output_key or final text into one Pydantic model."""
    if isinstance(raw_output, output_schema):
        return raw_output
    if isinstance(raw_output, BaseModel):
        return output_schema.model_validate(raw_output.model_dump(mode="json"))
    if isinstance(raw_output, dict):
        return output_schema.model_validate(raw_output)
    if isinstance(raw_output, str):
        text = _strip_json_fence(raw_output)
        return output_schema.model_validate_json(text)
    return output_schema.model_validate(raw_output)


def _strip_json_fence(text: str) -> str:
    """Strip a simple Markdown JSON code fence when a provider returns one."""
    stripped = str(text or "").strip()
    if not stripped.startswith("```"):
        return stripped
    lines = stripped.splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()


def _json_dump(value: Any) -> str:
    """Dump prompt variables as stable JSON."""
    return json.dumps(value, ensure_ascii=False, indent=2)
