from typing import AsyncGenerator, List, Dict
from typing_extensions import override
from concurrent.futures import ThreadPoolExecutor
import time
import asyncio

from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Content, Blob

from src.logger import logger
from conf.system import SYS_CONFIG
from src.agents.experts.image_editing.tool import segmind_GPT_image_1_tool

class ImageEditingAgent(BaseAgent):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
        self,
        name: str,
        description: str = "",
    ) -> None:
        """Initializes the ImageEditingAgent."""

        super().__init__(
            name=name,
            description=description
        )

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Runs the ImageEditingAgent asynchronously.

        This method orchestrates the sequence of agents to generate an image from text.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image editing process.
        """
        current_parameters = ctx.session.state.get('current_parameters', {})

        if ('input_name' not in current_parameters) or ('prompt' not in current_parameters):
            error_text = f"Missing parameters for {self.name}. Required fields: input_name, prompt"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output}) 
            return

        rsp = await segmind_GPT_image_1_tool(ToolContext(ctx))    
        step = ctx.session.state['step']

        if rsp["status"] == "error":
            error_text = f"round{step+1}: {self.name} execution failed: {rsp['message']}"
            current_output = {"status": "error", "message": error_text}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output":current_output}) 
            return
        
        else:
            # save artifact
            prompt_list = current_parameters['prompt']
            if not isinstance(prompt_list, list): prompt_list = [prompt_list]
            text = f"Round {step+1}: {self.name} finished editing {len(prompt_list)} image(s)."
            output_artifacts = []

            for i,(prompt, message) in enumerate(zip(prompt_list, rsp['message'])):
                if not message:
                    text += f"\nImage {i+1} editing failed. Prompt: {prompt}."

                artifact_name = f"step{ctx.session.state.get('step')+1}_editing_output{i}.png"
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=message))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id, filename=artifact_name, artifact=artifact_part
                )

                text += f"\nImage {i+1} editing succeeded. Output artifact: {artifact_name}"
                description = f"new image edited based on the original image: {current_parameters['input_name']}, the editing instruction is: {prompt}"
                
                output_artifacts.append({'name': artifact_name, 'description':description})

            # output event
            current_output = {
                "status": "success",
                "message": text,
                "output_artifacts": output_artifacts
            }
            yield self.format_event(text, {'current_output':current_output})
            return
