from typing import AsyncGenerator, Dict
from typing_extensions import override

from google.adk.agents import BaseAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Content

from src.logger import logger
from src.agents.experts.image_editing import tool as editing_tools
from src.runtime.workspace import build_workspace_file_record, save_binary_output

class ImageEditingAgent(BaseAgent):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
        self,
        name: str,
        description: str = "",
    ) -> None:
        """Initializes the ImageEditingAgent."""

        super().__init__(
            name=name,
            description=description
        )

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Runs the ImageEditingAgent asynchronously.

        This method orchestrates the sequence of agents to generate an image from text.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image editing process.
        """
        current_parameters = ctx.session.state.get('current_parameters', {})

        input_paths = current_parameters.get("input_paths", current_parameters.get("input_path"))
        if input_paths is None or ('prompt' not in current_parameters):
            error_text = f"Missing parameters for {self.name}. Required fields: input_path or input_paths, prompt"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output}) 
            return

        prompt_list = current_parameters["prompt"]
        if isinstance(prompt_list, str):
            prompt_list = [prompt_list]
        provider = str(current_parameters.get("provider", "nano_banana")).strip().lower()

        if provider == "seedream":
            rsp = await editing_tools.seedream_image_edit_tool(ToolContext(ctx), prompt_list)
        else:
            rsp = await editing_tools.nano_banana_image_edit_tool(ToolContext(ctx), prompt_list)
        step = ctx.session.state['step']

        if rsp["status"] == "error":
            error_text = f"round{step+1}: {self.name} execution failed: {rsp['message']}"
            current_output = {"status": "error", "message": error_text}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output":current_output}) 
            return
        
        else:
            # save artifact
            text = f"Round {step+1}: {self.name} finished editing {len(prompt_list)} image(s)."
            output_artifacts = []

            for i,(prompt, message) in enumerate(zip(prompt_list, rsp['message'])):
                if not message:
                    text += f"\nImage {i+1} editing failed. Prompt: {prompt}."
                    continue

                output_path = save_binary_output(
                    message,
                    session_id=ctx.session.id,
                    step=ctx.session.state.get('step') + 1,
                    output_type="editing",
                    index=i,
                    extension=".png",
                )
                artifact_name = output_path.name

                text += f"\nImage {i+1} editing succeeded. Output file: {artifact_name}"
                description = (
                    f"new image edited based on the original workspace files: "
                    f"{input_paths}, the editing instruction is: {prompt}"
                )
                
                output_artifacts.append(
                    build_workspace_file_record(
                        output_path,
                        description=description,
                        source="expert",
                        name=artifact_name,
                    )
                )

            if not output_artifacts:
                error_text = f"round{step+1}: {self.name} execution failed: all edited images were empty."
                current_output = {"status": "error", "message": error_text}
                logger.error(error_text)
                yield self.format_event(error_text, {"current_output": current_output})
                return

            # output event
            current_output = {
                "status": "success",
                "message": text,
                "output_files": output_artifacts
            }
            yield self.format_event(text, {'current_output':current_output})
            return
