import asyncio
from typing_extensions import override
from typing import AsyncGenerator, List, Dict

from google.adk.agents import LlmAgent
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part
from google.genai.types import Content

from conf.system import SYS_CONFIG
from src.agents.experts.image_understanding.tool import image_to_text_tool
from src.logger import logger

class ImageUnderstandingAgent(BaseAgent):
    """
    a custom agent for understanding image
    """

    model_config = {"arbitrary_types_allowed": True}
    def __init__(
        self,
        name: str,
        description: str = ""
    ) :
        super().__init__(
            name = name,
            description = description
        )

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Runs the ImageUnderstandingAgent asynchronously.

        This method achieves understand images.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        logger.info(f"[{self.name}] Starting understanding images.")
        current_parameters = ctx.session.state.get('current_parameters', {})
        if ('input_path' not in current_parameters and 'input_paths' not in current_parameters) or ('mode' not in current_parameters):
            error_text = f"Missing parameters provided to {self.name}, must include: input_path or input_paths, mode"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output})
            return

        input_paths = current_parameters.get("input_paths", current_parameters.get("input_path"))
        if isinstance(input_paths, str):
            input_paths = [input_paths]
        count = len(input_paths)

        tasks = [image_to_text_tool(ToolContext(ctx), path) for path in input_paths]
        result_list = await asyncio.gather(*tasks)

        sucess_message_list = []
        error_message_list = []
        for path, result in zip(input_paths, result_list):
            if result['status'] == 'success':
                sucess_message_list.append(f"image {path} description: {result['message']}\n")
            elif result['status'] == 'error':
                error_message_list.append(f"image {path} description failed, reason: {result['message']}\n")

        if len(error_message_list) == count:
            error_text = f"All {count} images description failed:\n\n" + '\n'.join(error_message_list)
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)
            yield self.format_event(error_text, {"current_output":current_output})
            return

        message = f"Finishing describe {count} images with {len(sucess_message_list)} images successfully described\n\n"
        output_text = message + '\n'.join(sucess_message_list+error_message_list)      

        current_output = {
            "status": "success",
            "message":message,
            'output_text':output_text
        }

        yield self.format_event(output_text, {'current_output':current_output})
        return
