from typing import AsyncGenerator, List, Dict
from typing_extensions import override
import time
import asyncio

from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob, Content
from src.utils import SYS_CONFIG
from src.logger import logger
from src.agents.experts.image_generation.tool import tongyi_text2image_tool, prompt_enhancement_tool, GPTimage1_text2image_tool


class ImageGenerationAgent(BaseAgent):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""
    model_config = {"arbitrary_types_allowed": True}

    def __init__(
        self,
        name: str,
        description: str = "",
    ) -> None:
        """Initializes the Text2ImageAgent."""

        sub_agents_list: List[BaseAgent] = []
        super().__init__(
            name=name,
            sub_agents=sub_agents_list,
            description=description,
        )


    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event

    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """
        
        current_parameters = ctx.session.state.get('current_parameters', {})
        if 'prompt' not in current_parameters:
            error_text = f"Missing parameters provided to {self.name}, must include: prompt"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output})
            return

        original_prompt = current_parameters['prompt'] 
        if isinstance(original_prompt, str): original_prompt = [original_prompt]

        # prompt enhancement
        tasks = [prompt_enhancement_tool(ctx, prompt) for prompt in original_prompt]
        result_list = await asyncio.gather(*tasks)
        prompt_list = []
        for i, result in enumerate(result_list):
            if result['status'] == 'success':
                prompt_list.append(result['message'])
            else:
                logger.warning(f"{self.name}: prompt enhance failed, use original prompt")
                prompt_list.append(original_prompt[i])

        tasks = [GPTimage1_text2image_tool(prompt) for prompt in prompt_list]
        result_list = await asyncio.gather(*tasks)

        output_artifacts = []
        message = []
        for i, (prompt, result) in enumerate(zip(prompt_list, result_list)):
            if result['status'] == 'error':
                message.append(f"image generation task{i+1} failed: {result['message']}")
            else:
                message.append(f"image generation task{i+1} success")
                artifact_name = f"step{ctx.session.state.get('step')+1}_generation_output{i}.png"
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=result["message"]))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id, filename=artifact_name, artifact=artifact_part
                )

                description = f"The {i+1}th image generated by image generation tool in round{ctx.session.state.get('step')+1}, prompt is {prompt}"
                output_artifacts.append({'name':artifact_name, 'description':description})
        
        if len(output_artifacts)==0:
            message = f"{self.name} all {len(result_list)} image generation tasks failed: {','.join(message)}"
            logger.error(message)
            current_output = {'status': 'error', 'message': message}
            
        else:
            message = f"{self.name} has completed {len(result_list)} image generation tasks: {','.join(message)}"
            logger.info(message)
            current_output = {'status': 'success', 'message': message, 'output_artifacts': output_artifacts}

        yield self.format_event(message, {"current_output":current_output})
        return
