"""Music generation expert for Creative Claw."""

from __future__ import annotations

from typing import Any, AsyncGenerator
from typing_extensions import override

from google.adk.agents import BaseAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.genai.types import Content, Part

from src.agents.experts.music_generation.tool import (
    _parse_bool,
    music_generation_tool,
    normalize_music_audio_format,
)
from src.runtime.workspace import build_workspace_file_record, save_binary_output


class MusicGenerationExpert(BaseAgent):
    """Generate one music or BGM clip from text instructions."""

    model_config = {"arbitrary_types_allowed": True}

    def __init__(self, name: str, description: str = "") -> None:
        """Initialize the music generation expert."""
        super().__init__(name=name, description=description)

    def format_event(
        self,
        content_text: str | None = None,
        state_delta: dict[str, Any] | None = None,
    ) -> Event:
        """Build one ADK event with optional content and state updates."""
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role="model", parts=[Part(text=content_text)])
        return event

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Run one music generation request."""
        current_parameters = ctx.session.state.get("current_parameters", {})
        prompt = str(current_parameters.get("prompt", "")).strip()
        lyrics = str(current_parameters.get("lyrics", "")).strip()
        instrumental = _parse_bool(current_parameters.get("instrumental", not bool(lyrics)))
        audio_format = normalize_music_audio_format(current_parameters.get("audio_format", "mp3"))
        sample_rate = int(current_parameters.get("sample_rate", 44100) or 44100)
        bitrate = int(current_parameters.get("bitrate", 256000) or 256000)
        model = str(current_parameters.get("model", "music-2.5")).strip() or "music-2.5"

        if not prompt:
            error_text = f"Missing parameters provided to {self.name}, must include: prompt"
            current_output = {"status": "error", "message": error_text}
            yield self.format_event(error_text, {"current_output": current_output})
            return

        result = await music_generation_tool(
            prompt=prompt,
            lyrics=lyrics,
            instrumental=instrumental,
            audio_format=audio_format,
            sample_rate=sample_rate,
            bitrate=bitrate,
            model=model,
        )
        if result["status"] != "success":
            current_output = {"status": "error", "message": result["message"]}
            yield self.format_event(result["message"], {"current_output": current_output})
            return

        current_turn = int(ctx.session.state.get("turn_index", 0) or 0)
        current_step = int(ctx.session.state.get("step", 0) or 0)
        current_expert_step = int(ctx.session.state.get("expert_step", 0) or 0)
        output_path = save_binary_output(
            result["message"],
            session_id=ctx.session.id,
            turn_index=current_turn,
            step=current_step,
            output_type="music_generation",
            index=0,
            extension=f".{audio_format}",
        )
        output_record = build_workspace_file_record(
            output_path,
            description=(
                f"Music generated by MiniMax with model={result.get('model_name', '')}, "
                f"format={audio_format}, instrumental={result.get('instrumental', False)}."
            ),
            source="expert",
            name=output_path.name,
            turn=current_turn,
            step=current_step,
            expert_step=current_expert_step,
        )
        generation_result = {
            "output_path": output_record["path"],
            "audio_format": audio_format,
            "instrumental": bool(result.get("instrumental", False)),
            "lyrics_used": str(result.get("lyrics_used", "")).strip(),
            "provider": str(result.get("provider", "")).strip(),
            "model_name": str(result.get("model_name", "")).strip(),
        }
        message = f"{self.name} generated 1 music file: {output_path.name}"
        current_output = {
            "status": "success",
            "message": message,
            "message_for_user": message,
            "output_text": message,
            "output_files": [output_record],
            "results": [generation_result],
        }
        yield self.format_event(
            message,
            {
                "current_output": current_output,
                "music_generation_results": [generation_result],
            },
        )
