from typing import AsyncGenerator, List, Optional, Any, Dict
import json, uuid
import re
import os.path as osp

from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.artifacts import InMemoryArtifactService
from google.adk.events import Event, EventActions
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai.types import Content, Part, Blob

from src.logger import logger
from google.adk.agents import LlmAgent
from conf.system import SYS_CONFIG
from conf.agent import experts_list

avaliable_agents: str = '\n'.join([str(expert) for expert in experts_list if expert.enable])


def clean_and_parse_json(json_string: str) -> Dict[str, Any]:
    cleaned_string = re.sub(r'^```(json)?\s*|\s*```$', '', json_string.strip(), flags=re.MULTILINE)
    try:
        return json.loads(cleaned_string)
    except json.JSONDecodeError:
        logger.error(f"JSON decoding failed, original string: '{json_string}'")
        return {}
    
class ExecutorAgent(BaseAgent):
    """
    The executor agent that generate plan
    """
    planner: LlmAgent
    execute_enabled: bool

    def __init__(
        self,
        name:str,
        description:str,
        llm_model: str = '',
        execute_enabled: bool = False,
    ):
        if not llm_model:
            llm_model = SYS_CONFIG.llm_model
        logger.info(f"ExecutorAgent: using llm: {llm_model}")

        planner = LlmAgent(
            name="PlannerAgent",
            model=llm_model,
            description='Analyze input request, output a plan in json format in order to successive execution.',
            instruction=EXECUTOR_INSTRUCTION + avaliable_agents
        )

        super().__init__(
            name=name,
            description=description,
            planner = planner,
            execute_enabled = execute_enabled
        )

        

    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Run the executor agent
        if self.execute_enabled==True: executor will generate a plan on itself
        otherwise, it directly use the plan stored in state

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the plan generation process.

        """
        
        async for event in self.planner.run_async(ctx):
            if event.is_final_response() and event.content and event.content.parts:
                final_response_text = ''
                text_part = next(
                    (part.text for part in event.content.parts if part.text), None
                )
                if text_part:
                    final_response_text = text_part

                # new plan generated by executor agent
                plan = clean_and_parse_json(final_response_text)

                if 'next_agent' in plan and 'parameters' in plan:
                    yield Event(
                        author='api_server',
                        content=None,
                        actions=EventActions(state_delta=plan)
                    )

class Executor:
    def __init__(
        self,
        session_service: InMemorySessionService,
        artifact_service: InMemoryArtifactService,
        app_name: str = SYS_CONFIG.app_name,
        save_dir: str = '',
        uid: str = '',
        sid: str = '',
        llm_model: str = '',
        expert_runners: Dict[str, Runner] = {},
        execute_enabled: bool = False
    ) -> None:
        self.app_name = app_name
        self.session_service = session_service
        self.artifact_service = artifact_service
        self.save_dir = save_dir
        self.uid = uid
        self.sid = sid
        self.execute_enabled = execute_enabled
        if not llm_model:
            llm_model = SYS_CONFIG.llm_model
        logger.info(f"ExecutorAgent: using llm: {llm_model}")

        self.expert_runners = expert_runners

        self.executor_agent = ExecutorAgent(
            name="ExecutorAgent",
            description="",
            llm_model=llm_model,
            execute_enabled=execute_enabled
        )

        self.executor_runner = Runner(agent=self.executor_agent, app_name=self.app_name, session_service=self.session_service, artifact_service=self.artifact_service)

    @staticmethod
    def build_runner_message(instruction: str) -> Content:
        """Create a minimal ADK-compatible user message for a new invocation."""
        return Content(role="user", parts=[Part(text=instruction)])

    async def run_agent_and_log_events(
        self, runner: Runner, user_id: str, session_id: str, new_message: Optional[Content] = None
    ) -> str:
        final_response_text = ""
        async for event in runner.run_async(
            user_id=user_id,
            session_id=session_id,
            new_message=new_message,  # type: ignore
        ):
            logger.debug(f"Event: {event.model_dump_json(indent=2, exclude_none=True)}")
            if event.is_final_response() and event.content and event.content.parts:
                text_part = next(
                    (part.text for part in event.content.parts if part.text), None
                )
                if text_part:
                    final_response_text = text_part
                    logger.info(
                        f"[{runner.agent.name}] final output text: '{final_response_text}'"
                    )
        return final_response_text
    
    async def add_event(self, text:str='', state_delta:Dict=None):

        if text:
            event = Event(
                author='api_server',
                content=Content(role='model', parts=[Part(text=text)]),
                actions=EventActions(state_delta=state_delta)
            )
        else:
            event = Event(
                author='api_server',
                actions=EventActions(state_delta=state_delta)
            )

        current_session = await self.session_service.get_session(
            app_name=self.app_name,
            session_id=self.sid,
            user_id=self.uid
        )

        await self.session_service.append_event(current_session, event)

    async def save_artifact(self, art_name: str, current_uid:str, current_sid:str):
        art_part = await self.artifact_service.load_artifact(
            app_name=self.app_name, user_id=self.uid, session_id=self.sid, filename=art_name
        )

        art_name = f"{current_uid}_{current_sid}_{art_name}"
        art_path = osp.join(self.save_dir, art_name)
        with open(art_path, mode='wb') as f:
            f.write(art_part.inline_data.data)
        return art_path
    


    async def execute_plan(self):
        # plan = await self.run_agent_and_log_events(self.executor_runner, session_id=self.sid, user_id=self.uid)

        # plan = clean_and_parse_json(plan)

        if self.execute_enabled:
            await self.run_agent_and_log_events(
                self.executor_runner,
                session_id=self.sid,
                user_id=self.uid,
                new_message=self.build_runner_message(
                    "Generate the next execution step from the current session state."
                ),
            )

        # load state['current_plan']
        current_session = await self.session_service.get_session(app_name=self.app_name, user_id=self.uid, session_id=self.sid)

        plan = current_session.state.get('current_plan')

        next_agent_name = plan.get("next_agent")
        params_for_expert = plan.get("parameters", {})
        final_summary = plan.get("summary", {})

        if next_agent_name not in self.expert_runners:
            error_text = f"Executor got an unknown Agent: '{next_agent_name}', which is not in the privided agent list."
            logger.error(error_text)

            await self.add_event(text=error_text)
            return
        
        # check if artifact name exists
        if 'input_name' in params_for_expert:
            art_list = await self.artifact_service.list_artifact_keys(
                app_name=self.app_name, user_id=self.uid, session_id=self.sid
            )
            input_names = []
            if isinstance(params_for_expert['input_name'], str):
                input_names = [params_for_expert['input_name']]
            elif isinstance(params_for_expert['input_name'], list):
                input_names = params_for_expert['input_name']
            else:
                error_text = "current plan parameters['input_name'] must be a string or a list"
                logger.error(error_text)
                await self.add_event(text=error_text)
                return         
            
            for name in input_names:
                if name in art_list:
                    continue
                error_text = f"Executor got an unknown artifact: '{name}', which is not in the artifact list."
                logger.error(error_text)

                await self.add_event(text=error_text)
                return

        # write current parameters to state
        await self.add_event(state_delta={'current_parameters': params_for_expert})
        # run expert
        expert_runner = self.expert_runners[next_agent_name]
        await self.run_agent_and_log_events(
            expert_runner,
            user_id=self.uid,
            session_id=self.sid,
            new_message=self.build_runner_message(
                f"Execute the current step with agent {next_agent_name} using parameters stored in session state."
            ),
        )

        # write output to state after finishing execution
        # Output location: state['current_output'] = {'state', 'output_artifacts', 'message'}
        current_session = await self.session_service.get_session(
            app_name=self.app_name, user_id=self.uid, session_id=self.sid
        )
        current_step = current_session.state.get('step')
        current_output = current_session.state.get('current_output')
        artifacts_history = current_session.state.get('artifacts_history')
        text_history = current_session.state.get('text_history')
        message_history = current_session.state.get('message_history')
        summary_history = current_session.state.get('summary_history')

        if not current_output:
            current_output = {'status': 'pending'}

        state_delta = {
            'step': current_step+1,
        }

        # save new artifact to local
        if current_output['status'] == 'success' and 'output_artifacts' in current_output:
            for art in current_output['output_artifacts']:
                current_sid = current_session.state['sid']
                current_uid = current_session.state['uid']
                logger.info(f"saving artifact {art['name']}")
                art_path = await self.save_artifact(art['name'], current_uid, current_sid)
                art['path'] = art_path

                logger.info(f"saved to {art_path}")

        # generate an event and append it to session
        if current_output['status'] == 'success':
            # save output_artifacts and artifacts_history
            if 'output_artifacts' in current_output:
                state_delta['new_artifacts'] = current_output['output_artifacts']
                state_delta['artifacts_history'] = artifacts_history+[current_output['output_artifacts']]
            else:
                state_delta['new_artifacts'] = []
                state_delta['artifacts_history'] = artifacts_history+[[]]

            # save text_history
            if 'output_text' in current_output:
                state_delta['text_history'] = text_history+[current_output['output_text']]
            else:
                state_delta['text_history'] = text_history+[None]

            # save summary_history
            state_delta['summary_history'] = summary_history + [final_summary]

            # save message_history
            state_delta['message_history'] = message_history + [current_output['message']]
            
            await self.add_event(text=f"Round{current_step+1} execution has been completed. The original target of this step: `{final_summary}`, the summary after execution: `{current_output['message']}`", state_delta=state_delta)

        elif current_output['status'] == 'error':
            state_delta['new_artifacts'] = []
            state_delta['artifacts_history'] = artifacts_history+[[]]
            state_delta['text_history'] = text_history + [None]
            state_delta['message_history'] = message_history + [current_output['message']]
            state_delta['summary_history'] = summary_history + [final_summary]

            await self.add_event(text=f"Round {current_step+1} hit an execution error. The original target of this step was `{final_summary}` and the error was `{current_output['message']}`. The goal may still be incomplete and might need to be retried with improved parameters or a better method.", state_delta=state_delta)

        return current_output


EXECUTOR_INSTRUCTION = """
You are the executing AI of the art creation pipeline. Your task is to continuously analyze a shared 'state' in a loop and decide which expert agent and parameters to call next, until the entire multi-step user task is completed.

** You need to view the dialogue history and parameters in the state to understand the current task planning and status

** Your output must be a JSON object.**
**JSON output format**
```json
{{
    "next_agent": "AgentName",
    "parameters": {{
    "param1_for_agent": "value1"
    }},
    "summary": "A brief summary of your current decision, which will be presented to the user."
}}
```

**Key instructions: **
1.  **End signal**: If you determine that current task has been completely completed, you must set the value of 'next_agent' to 'null' or 'FINISH'. This is the only way to terminate the loop.
2.  **Pay attention ot intermediate products**: You must check the output file names generated by other agents in the previous steps, and use these outputs to prepare the parameters for the next step.
3.  **Accurate task assignment**: For image generation and editing, special attention should be paid to the user's intention. Some image generation tasks require reference, such as images input by the user or images output from previous steps, or when the user mentions "generation based on or reference ***", an agent with reference image generation function is needed instead of purely generation through prompt text.

**Workflow:**

1.  **Analyze the current status**:
    - Carefully read the user input task: `{user_prompt}`.
    - If the file that needs to be operated on is provided, you need to review the provided file and check if it has achieved the planning goals of the previous step.

2.  **Decision making and parameter preparation**:
    - If the previous planning step is not completed, consider the reasons for the failure and re-execute it using improved methods.
    - Prepare a 'parameters' dict containing all necessary parameters for the experts involved.

# Expert Agent List:\n\n
"""
